#!/bin/bash

# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to firefox.
# Anything else, it search it.

pgrep -x dmenu && exit

shopt -s nocasematch

choice=$(dmenu -i -p "Search DuckDuckGo:") || exit 1

if [ "$choice" = "🦆"  ]; then
    firefox "https://duckduckgo.com"
else
    # Detect if url
    if [[ "$choice" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
        firefox "$choice"
    elif [[ $choice == "portal" ]]; then
        firefox "https://portal.azure.com/"
    else
        firefox "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
    fi
fi
